[package]
name = "persian-tools-cli"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = {version = "4.5.4", features = ["derive"]}
rust-persian-tools = "1.1.3"

[profile.release]
opt-level = 3
overflow-checks = false
lto = false
codegen-units = 1
